this  forwardref  for the select.
locoworks/reusejs-react pull request #38
Opened 2023-06-30 05:00 UTC by Ayush2020012016

- [ ] Added the forward ref for the select.
- [ ] Added the documentation for the select.

2023-06-30 05:42 UTC, ShreyDhyani requested changes
@Ayush2020012016 Pls make the requested changes

2023-06-30 05:42 UTC, ShreyDhyani commented on components/select-dropdown/src/ReuseSelectDropdown.tsx
> +console.log("this is form the select base file.",{ref})
Remove this log

2023-06-30 05:42 UTC, ShreyDhyani commented on development/select-dropdown-app/components/select-dropdown/ForwardRefSelectDropdown/ForwardRefSelectDropdown.jsx
> +// optionsRenderer={(
Remove this comment

2023-06-30 05:42 UTC, ShreyDhyani commented on development/select-dropdown-app/components/select-dropdown/ForwardRefSelectDropdown/ForwardRefSelectDropdown.tsx
> +// optionsRenderer={(
This too.

2023-06-30 05:42 UTC, ShreyDhyani commented on development/select-dropdown-app/pages/select-dropdown/index.mdx
> +import ForwardRefSelectDropdown from "../../components/select-dropdown/ForwardRefSelectDropdown/ForwardRefSelectDropdown.jsx"
Use tsx file here

2023-07-04 15:59 UTC, Ayush2020012016 reviewed
removed the logs and comments.

2023-07-04 16:00 UTC, Ayush2020012016 commented
@ShreyDhyani please review this and please merge. thankyou

2023-07-05 04:09 UTC, ShreyDhyani approved these changes

2023-07-05 04:09 UTC, merged