Table filter
locoworks/reusejs-react pull request #73
Opened 2023-07-25 11:08 UTC by AMIRSOHAIL1998

## Changes in PR.
- [x] Added DataTable Example for Search in Whole GTable
- [x]  Added Column base search Example
- [x] Added Nested Search Example 
- [x] Updated Docs with given format , mars-issuse: [Link for Docs Guide](https://mars.betalectic.com/locoworks/reusejs-react/-/issues/40)
- [x] Updated Docs for UseDataTable Hook with given format,  mars-issuse: [Link for Docs Guide](https://mars.betalectic.com/locoworks/reusejs-react/-/issues/40)

2023-07-26 06:03 UTC, ShreyDhyani requested changes

2023-07-26 06:09 UTC, AMIRSOHAIL1998 commented on components/data-table/src/HeadlessDataTableWithFilter.tsx
> +			className={
No There is Difference, HeadlessDataTable only responsible for Data Rendering with Pagination, But  HeadlessDataTableWithFilter is a component which is also responsible for search and filtering with above feature.

2023-07-26 06:14 UTC, ShreyDhyani commented on components/data-table/src/HeadlessDataTableWithFilter.tsx
> +			className={
How will the table ui be different?

2023-07-26 06:17 UTC, AMIRSOHAIL1998 commented on components/data-table/src/HeadlessDataTableWithFilter.tsx
> +			className={
With the custom Styling Because Styling is has to be given by user. From outside of the component as props.

2023-07-26 06:26 UTC, AMIRSOHAIL1998 commented on components/data-table/src/HeadlessDataTableWithFilter.tsx
> +	tableData: any;
Both Are independent component, some when want to use our hook only no need to use component, and and some user wants to use component he does not care about hook.

that's created separated for hook and as well as for component.

2023-07-26 06:28 UTC, AMIRSOHAIL1998 commented on components/data-table/src/HeadlessDataTableWithFilter.tsx
> +	tableData: any;
and also both are different interface just named as Same.

2023-08-03 12:00 UTC, ShreyDhyani requested changes

2023-12-05 10:44 UTC, AMIRSOHAIL1998 commented on development/data-table-app/components/data-table/FilterDataTable/FilterDataTable.tsx
> +		"Contact Details": string;
removed and updated code to capitalize heading and removed `_` and add space

2023-12-05 10:44 UTC, AMIRSOHAIL1998 commented on development/data-table-app/pages/data-table/index.mdx
> +- To utilize the Simple `DataTable` with Pagination or you require `Search` and `Filter` functionalities in addition to `Pagination`  then you should utilize `HeadlessDataTable`.
This is upadated

2023-12-05 10:46 UTC, AMIRSOHAIL1998 commented on development/data-table-app/pages/data-table/index.mdx
> +- The `HeadlessDataTable` component uses the `useDataTable` hook from the `@locoworks/reusejs-toolkit-react-hooks` library to manage `pagination` and other functionalities. The hook returns various p
removed extra space and updated Props table

2023-12-05 10:50 UTC, AMIRSOHAIL1998 commented on development/data-table-app/pages/data-table/index.mdx
> +- When you use the `HeadlessDataTable` component, it automatically `paginates` the `tableData` based on the `itemsPerPage` prop. It also sets up navigation buttons to move between pages of data.
Removed Extra The and updated the pointer lines

2023-12-05 11:00 UTC, AMIRSOHAIL1998 commented on development/select-dropdown-app/components/select-dropdown/ReuseSelect/ReuseSelect.jsx
> +	const options = [
there is no change basically due not taking latest pull from that's why this was show updated this one also

2023-12-05 13:11 UTC, merged